name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd NitroCppTest-Erdem
        cmake -B build
        cmake --build build --config Debug
    - name: unit-tests
      run: |
        cd NitroCppTest-Erdem/build
        ctest --verbose -C Debug
    - name: integration-tests
      run: |
         cd NitroCppTest-Erdem/tests/integration 
         python3 test.py


  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd NitroCppTest-Erdem
        cmake -B build
        cmake --build build --config Debug
    - name: unit-tests
      run: |
        cd NitroCppTest-Erdem\build
        ctest --verbose -C Debug
    - name: integration-tests
      run: |
         cd NitroCppTest-Erdem\tests\integration 
         python3 test.py