name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    name: Build and Test Project on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cmake -B build
        cmake --build build/
    - name: tests
      run: |
         cd build 
         ctest --verbose

  build-windows:
    name: Build and Test Project on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cmake -B build
        cmake --build build/
    - name: tests
      run: |
         cd build 
         ctest --verbose